@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedFirstImpressions" as VersionedFirstImpressions MODEL_COLOR
end box

[-> Model : undoFirstImpressions()
activate Model

Model -> VersionedFirstImpressions : undo()
activate VersionedFirstImpressions

VersionedFirstImpressions -> VersionedFirstImpressions :resetData(ReadOnlyFirstImpressions)
VersionedFirstImpressions --> Model :
deactivate VersionedFirstImpressions

[<-- Model
deactivate Model

@enduml
